feat: 6867 6868 image and dot opacity
chanzuckerberg/single-cell-explorer pull request #1029
Opened 2024-07-09 17:29 UTC by tihuan

<img width="1112" alt="Screenshot 2024-07-09 at 10 26 19 AM" src="https://github.com/chanzuckerberg/single-cell-explorer/assets/6309723/89281c10-21a0-46ba-bc79-10b398bc722d">
<img width="1232" alt="Screenshot 2024-07-09 at 10 26 26 AM" src="https://github.com/chanzuckerberg/single-cell-explorer/assets/6309723/a5280955-b0c3-44b6-95a8-c38925abd47a">
<img width="1513" alt="Screenshot 2024-07-09 at 10 26 33 AM" src="https://github.com/chanzuckerberg/single-cell-explorer/assets/6309723/949798ea-6856-4db9-9454-362880d91e7a">

https://github.com/chanzuckerberg/single-cell-explorer/assets/6309723/22235e0b-cb9b-415f-84ed-a7506522b17f

2024-07-09 17:35 UTC, tihuan commented on client/src/components/menubar/index.tsx
> -  panelEmbedding: RootState["panelEmbedding"];
moved the image toggle button to `Embedding` component, so we no longer need these props here

2024-07-09 17:35 UTC, tihuan commented on client/src/reducers/controls.ts
> +  dotOpacity: number;
new redux state for both opacities

2024-07-09 17:35 UTC, tihuan commented on client/src/components/embedding/components/Opacities/components/Opacity/index.tsx
> +      <HeaderWrapper>
Opacity component has the input text box and the slider

2024-07-09 17:35 UTC, tihuan commented on client/src/components/embedding/components/Opacities/index.tsx
> +function Opacities({ imageOpacity, dotOpacity, dispatch }: Props) {
`Opacities` component hosts both types of opacity control

2024-07-09 17:35 UTC, tihuan commented on client/src/components/embedding/index.tsx
> +  imageUnderlay: RootState["controls"]["imageUnderlay"];
Embedding component now needs these props to determine whether to show the Image toggle button and its dropdown or not

2024-07-09 17:35 UTC, tihuan commented on client/src/components/embedding/index.tsx
> +          <Tooltip2
upgrade to Tooltip2 as a bonus

2024-07-09 17:35 UTC, tihuan commented on client/src/components/embedding/index.tsx
> +                />
existing code moved here

2024-07-09 17:35 UTC, tihuan commented on client/src/components/embedding/index.tsx
> +              </Popover2>
the new pop over that shows Opacities control as its content

2024-07-09 17:35 UTC, tihuan commented on client/src/components/graph/graph.tsx
> +  initOpenSeadragon() {
update the name to reflect its actual functionality

2024-07-09 18:11 UTC, kaloster approved these changes

2024-07-09 22:38 UTC, hthomas-czi requested changes
Looks great, Timmy! I just see a couple things that would be great to fix.

1. The "Image Opacity" and "Dot Opacity" labels should use the same style as the "Standard Categories" label.
2. Clicking outside of the opacity popover (and the embedding popover actually) to dismiss it doesn't work as expected. It only works if you click outside of the main center workspace (i.e., one of the sidebars or the inline with the toolbar) 

This isn't from this PR but it'd also be nice to fix the position of the cell count. It should be left aligned with the embedding selector icon. It appears to be shifted over because of the color legend, but it looks weird when the user isn't coloring by a continuous variable. Ideally, the color legend would appear below the cell count.

2024-07-09 22:40 UTC, tihuan commented
Ohh eagle eye 🦅 👁️!! Thanks so much, Harley! Will address all 3 👍 

Also I need to investigate the failing e2e tests HMM!

2024-07-11 15:14 UTC, tihuan commented
@hthomas-czi okay all 3 issues should be address now 😄 PTAL again and thanks again for catching them!

<img width="1365" alt="Screenshot 2024-07-11 at 8 11 52 AM" src="https://github.com/chanzuckerberg/single-cell-explorer/assets/6309723/6a1b6566-c6be-4f45-be65-00ea23ba4f77">

<img width="926" alt="Screenshot 2024-07-11 at 8 12 03 AM" src="https://github.com/chanzuckerberg/single-cell-explorer/assets/6309723/0b832f80-7050-47ff-9c03-9d9d4128b394">


https://github.com/chanzuckerberg/single-cell-explorer/assets/6309723/43ea1cef-0a56-4376-99b8-8ef252cd6ef9

2024-07-11 15:15 UTC, tihuan commented on client/src/components/NavBar/index.tsx
> +              hasBackdrop
adding backdrop creates a reliable way to detect click outside of the popover element

2024-07-11 16:45 UTC, hthomas-czi approved these changes
Looks good! Thanks, Timmy.

2024-07-11 17:00 UTC, tihuan commented
Thanks so much, Harley! 

Looks like I need to update the e2e tests. Will do that after my meetings!

2024-07-11 22:24 UTC, tihuan commented
Okay finally all passed lol Merging!

2024-07-11 22:24 UTC, merged