chore: clean up documentation and fix broken links.
chanzuckerberg/single-cell-explorer pull request #252
Opened 2022-05-06 20:46 UTC by maniarathi

### Reviewers

**Functional:** @MDunitz 

---

### Changes

#### Deletions

- Removed Zenodo badge (only relevant for cellxgene Desktop).
- Remove broken links that 404'd.

#### Modifications

- Updated links that were pointing to the cellxgene Desktop to direct to files in this repo. 
- Updated links that were pointing to the old docs site to the new one.

2022-05-09 17:57 UTC, MDunitz requested changes
One of the links doesnt work for me and I added a small nit around phrasing.

2022-05-10 02:08 UTC, maniarathi commented on README.md
> +Please see our [contributing guide](https://chanzuckerberg.github.io/cellxgene/posts/contribute) and don't hesitate to open an issue or send a pull request to improve cellxgene. Please see the [dev_d
Fixed!

2022-05-10 18:23 UTC, MDunitz approved these changes
lgtm thanks!

2022-05-13 14:56 UTC, ebezzi approved these changes

2022-05-13 19:50 UTC, merged